[package]
name = "gallus-hsg"
version = "1.0.0"
entrypoint = "lib.typ"
categories = [ "thesis" ]
description = "Thesis University of St. Gallen (HSG)"
authors = [ "Joshua Hürzeler <https://joshuah.ch>" ]
license = "MIT"
disciplines = [ ]
repository="https://github.com/joshuabeny1999/unisg-thesis-template-typst/"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "template-hsg.webp"

[tool.hsg]
author = "Test"
